### ISSUE TITLE
Update Chorot Column

### ISSUE THREAD

**Issue by ghost** [NSC-AD-BAS/DB-Team#8]
In Students Table - make valid values.

**Comment by ghost** [comment]
From Bob: I will look into it. 
I thin that was intended to be a year with a quarter designation. 
1 for fall, 2 for winter, etc. 

Our cohort would be 20151
The first would be 20141.

**Comment by ghost** [comment]
Updated Script to use Chorot Column Correctly.

**Comment by jcstager** [comment]
You are correct.

Sent from my Verizon Wireless 4G LTE DROID

Casey Riggin notifications@github.com wrote:

From Bob: I will look into it.
I thin that was intended to be a year with a quarter designation.
1 for fall, 2 for winter, etc.

Our cohort would be 20151
The first would be 20141.
